### ISSUE TITLE
AddMedia test is slightly misleading

### ISSUE THREAD

**Issue by ngw** [NYTimes/encoding-wrapper#45]
Hi, the library works very well, but I was extremely confused by

https://github.com/nytimes/encoding-wrapper/blob/master/encodingcom/media_test.go#L15

and I lost a lot of time using the Output parameter as Destination. AFAIK that parameter should contain something like `[]string{"ogg"}` and not a url, which looks more like an HTTP destination.
Considering there's basically no documentation the tests become very relevant and that is in my opinion misleading.

**Comment by fsouza** [comment]
@ngw I will adjust it to say mp4. Thanks for reporting!
